env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
